import axios from "axios";
import React, { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import ApexLineChart from "../components/ApexLineChart";

export default function Home() {
  const [word, setWord] = useState([]);
  const [wordCount, setWordCount] = useState([]);
  async function fetchData() {
    //fetch call for the data
    const response = await axios.get(
      "https://www.terriblytinytales.com/test.txt"
    );
    // const string = "He seems fairly content with (his) life. \n\n They're content to socialize with a very small circle of people."
    const data = response.data;
    //changing the data to remove all the special characters and spaces
    let a = data
      .replaceAll(/\s\s+/g, " ")
      .replaceAll(/(\r\n|\r|\n)/g, " ")
      .replaceAll(/[^a-zA-Z ]/g, "")
      .toLowerCase();
    a = a.replaceAll(/\s\s+/g, " ");
    a = a.trim();
    //converting the stream in to array
    const dataArray = a.split(" ");
    // console.log(dataArray.length);
    // using map data structure we count the number of occurrences
    let map = new Map();
    dataArray.map((val) => {
      if (map.get(val)) {
        map.set(val, map.get(val) + 1);
      } else {
        map.set(val, 1);
      }
    });

    //sorting the map based on the values
    map = new Map([...map].sort((a, b) => b[1] - a[1]));
    let wordstemp = [];
    let counttemp = [];

    //making arrays to pass the data to the chart as props
    map.forEach(function (val, key) {
      wordstemp.push(key);
      counttemp.push(val);
      // console.log(key, val);
    });
    //taking only 20
    wordstemp = wordstemp.slice(0, 21);
    counttemp = counttemp.slice(0, 21);
    setWord(wordstemp);
    setWordCount(counttemp);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.content}>
        <h1>Welcome to Terribly Tiny Tales!</h1>
        {word.length === 0 ? (
          <div>
            <h4>Get Chart</h4>
            <button className={styles.btn} onClick={fetchData}>
              Submit
            </button>
          </div>)
          :
          (
            <div>
              <h3>top 20 words with highest occurrence</h3>
            </div>
          )
        }
        {word.length > 0 && (
          <div className={styles.chart}>
            <ApexLineChart words={word} count={wordCount} />
          </div>
        )}
      </div>
    </div>
  );
}
